import { Josefin_Sans, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const josefin_sans = Josefin_Sans({
  variable: "--font-josefin-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${josefin_sans.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}
